version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '22:00'
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      
  - package-ecosystem: "docker"
    directory: '/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies
    commit-message:
      prefix: "chore"