name: 【Docker】 Build JavSP Docker
on:
  schedule:
    - cron: '0 16 * * 1'
  push:
    paths: [ "Dockerfile",".github/workflows/build_docker.yml" ]
  pull_request:
    paths: [ "Dockerfile",".github/workflows/build_docker.yml" ]
  workflow_dispatch: ~

jobs:
  Build_Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
          
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get Version
      id: get_version
      run: |
        URL=https://api.github.com/repos/Yuukiy/JavSP/tags
        echo "version=$(curl -s ${URL} | jq -r '.[0].name')" >> $GITHUB_OUTPUT

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/javsp
        tags: |
          type=raw,value=${{ steps.get_version.outputs.version }},enable=true
          type=raw,value=latest,enable=true
        labels: |
          org.opencontainers.image.author=KIMI360
          org.opencontainers.image.description="汇总多站点数据的AV元数据刮削器"
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.source=https://github.com/Yuukiy/JavSP
          org.opencontainers.image.title=${{ secrets.DOCKER_USERNAME }}/javsp
          org.opencontainers.image.url=https://github.com/kimi360/JavSP-Docker
          org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
        flavor: latest=false     

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/javsp:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/javsp:cache,mode=max
