name: 【Docker】 Push JavSP Readme

on:
  push:
    paths: [ "README.md" ]
  workflow_dispatch: ~
  
jobs:
  description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/javsp
          readme-filepath: README.md